### ISSUE TITLE
do not rely on Rust nightly

### ISSUE THREAD

**Issue by schnusch** [dandels/dmodman#12]
It seems like currently building with rust nighly is required, otherwise the following error occurs:

```
use of unstable library feature 'binary_heap_retain'
```

**Comment by dandels** [comment]
This is stable since 1.70, which was [released in June](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html). NixOS [seems to be at 1.69](search.nixos.org/packages?channel=23.05&show=rustc). 

Using such a recent feature was unintentional. Since this causes packaging issues I guess I'll make a bugfix release for this.

**Comment by dandels** [comment]
I found out that NixOS is getting a new release with a newer rustc later this month, while the current release is EOL in December. If it's all the same to you, I would prefer waiting for the problem to go away by itself (I don't have a lot of free time right now or in the near-future).

**Comment by schnusch** [comment]
You are right, I should be able to package it for unstable, it won't be made available in 23.05 anyway.
